let express=require("express")
let {addproduct,getproducts,getproduct,deleteproduct,updateproductdetails,updateproductimage,upload}=require("../controllers/productcont")
let router=express.Router()
router.post("/addproduct",upload.single("image"),addproduct)
router.get("/getproducts",getproducts)
router.get("/getproduct/:id",getproduct)
router.delete("/deleteproduct/:id",deleteproduct)
router.put("/updateproductdetails",updateproductdetails)
router.put("/updateproductimage",upload.single("image"),updateproductimage)
module.exports=router